"""Generate data/seed/REPORT.md from places.json and the seed caches."""
import os
from collections import Counter

import fetch_osm_crosscheck
import fetch_wikidata
from common import CACHE, CHECKED_AT, GOVERNORATES, HERE, REPO, load_json

OUT = os.path.join(REPO, "data", "seed", "REPORT.md")

# Enrichment order for the first 30: hubs first, then by visitor importance.
ENRICH_ORDER = [
    "grand-egyptian-museum", "giza-pyramids", "egyptian-museum",
    "national-museum-of-egyptian-civilization", "saqqara", "cairo-citadel",
    "museum-of-islamic-art", "al-muizz-street", "sultan-hassan-mosque",
    "coptic-museum", "hanging-church", "ibn-tulun-mosque", "dahshur",
    "qaitbay-citadel", "graeco-roman-museum", "kom-el-shoqafa",
    "karnak", "luxor-temple", "valley-of-the-kings", "temple-of-hatshepsut",
    "medinet-habu", "luxor-museum",
    "abu-simbel", "philae-temple", "nubia-museum", "kom-ombo-temple", "edfu-temple",
    "dendera-temple", "abydos-temple-of-seti-i", "saint-catherines-monastery",
]

# MoTA ticket-list rows deliberately NOT seeded as separate records.
TICKET_ROWS_FOLDED = [
    ("Panorama of the Roof (Baron Palace / Dendera / Philae)", "optional add-on; becomes prices.extras of the parent"),
    ("Audio guides (Egyptian, Luxor, Hurghada, Sharm museums)", "prices.extras of the museum"),
    ("Parking tickets (Giza, Saqqara, Mit Rahina, Tell Basta, Dendera, Abu Simbel, Kom Ombo)", "prices.extras of the site"),
    ("Pyramid of Khufu / Khafre / Menkaure, Sphinx private visit, Tomb of Meresankh III, Workers' Cemetery", "extras of giza-pyramids"),
    ("Step Pyramid from the southern entrance, Noblemen's & New Kingdom tombs, Serapeum, Mereruka, Southern Tomb, all-Saqqara ticket", "extras of saqqara"),
    ("Tomb of Tutankhamun, Seti I, Ramesses V/VI, Ay", "extras of valley-of-the-kings"),
    ("Tomb of Nefertari", "extra of valley-of-the-queens"),
    ("Tomb of Pashedu", "extra of deir-el-medina"),
    ("Tombs of Ramose, Menna & Nakht, Rekhmire & Sennefer, Userhat & Khonsu, Roy & Shuroy", "extras of tombs-of-the-nobles-luxor"),
    ("Tomb of Pabasa", "extra of el-assasif-tombs"),
    ("Temple of Mut; Sphinx Avenue", "extras/part of karnak (Avenue of Sphinxes needs Karnak + Luxor tickets)"),
    ("The Royal Tomb (Amarna)", "extra of tell-el-amarna"),
    ("Shunet al-Zebib & Kom al-Sultan", "extra of abydos-temple-of-seti-i"),
    ("Al-Manasterly Palace", "within the Nilometer ticket (rawda-nilometer)"),
    ("Al-Darb al-Ahmar Visitor Route", "a walking route, not a single place; candidate for a 'route' feature later"),
    ("Underwater Antiquities (Alexandria)", "diving activity; Alexandria Underwater Museum (proposed) recorded as closed"),
    ("Temple of Isis (Aswan list)", "small Ptolemaic temple in Aswan town; not matched to Wikidata - add later if wanted"),
    ("Celebrating the Sun Alignment (Abu Simbel)", "event pricing of abu-simbel"),
]

GOV_EN = {k: v[1] for k, v in GOVERNORATES.items()}


def table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


def link_q(q):
    return f"[{q}](https://www.wikidata.org/wiki/{q})" if q else "-"


def main():
    P = load_json(os.path.join(REPO, "data", "seed", "places.json"))
    notes = load_json(os.path.join(CACHE, "build_notes.json"), {})
    egym = load_json(os.path.join(CACHE, "egymonuments.json"))
    wl = load_json(os.path.join(CACHE, "wikipedia_lists.json"), {})
    osm = load_json(os.path.join(CACHE, "osm_crosscheck.json"), [])
    sites = load_json(os.path.join(HERE, "sites_curated.json"))
    man = load_json(os.path.join(HERE, "museums_manual.json"))
    wd = load_json(os.path.join(CACHE, "wikidata.json"))
    by_id = {p["id"]: p for p in P}
    L = []
    w = L.append

    museums = [p for p in P if p["kind"] == "museum"]
    sitesP = [p for p in P if p["kind"] == "site"]
    w("# EgyMuseums seed dataset: report")
    w("")
    w(f"Generated by `tools/seed/make_report.py` from `data/seed/places.json`. Sources checked {CHECKED_AT}.")
    w("")
    w(f"**{len(P)} places: {len(museums)} museums, {len(sitesP)} sites.** "
      f"Wikidata-backed: {sum(1 for p in P if p['wikidataId'])}; "
      f"with coordinates: {sum(1 for p in P if p['lat'] is not None)}; "
      f"linked to egymonuments.gov.eg: {sum(1 for p in P if p['links'].get('egymonuments'))}.")
    w("")

    # ---- counts ---------------------------------------------------------
    w("## 1. Counts")
    w("")
    w("### By kind and tier")
    w("")
    t = Counter((p["kind"], p["tier"]) for p in P)
    w(table(["kind", "major", "notable", "minor", "total"],
            [[k, t[(k, "major")], t[(k, "notable")], t[(k, "minor")],
              sum(t[(k, x)] for x in ("major", "notable", "minor"))] for k in ("museum", "site")]
            + [["**all**", sum(v for (k, x), v in t.items() if x == "major"),
                sum(v for (k, x), v in t.items() if x == "notable"),
                sum(v for (k, x), v in t.items() if x == "minor"), len(P)]]))
    w("")
    w("### By governorate")
    w("")
    g = Counter((p["governorate"], p["kind"]) for p in P)
    rows = []
    for gid in sorted(GOVERNORATES, key=lambda x: -(g[(x, "museum")] + g[(x, "site")])):
        rows.append([f"{GOV_EN[gid]} (`{gid}`)", g[(gid, "museum")], g[(gid, "site")],
                     g[(gid, "museum")] + g[(gid, "site")],
                     sum(1 for p in P if p["governorate"] == gid and p["tier"] == "major")])
    w(table(["governorate", "museums", "sites", "total", "major"], rows))
    w("")
    for field in ("category", "operator", "status", "confidence"):
        c = Counter((p.get(field), p["kind"]) for p in P)
        vals = sorted({k for k, _ in c}, key=lambda v: -(c[(v, "museum")] + c[(v, "site")]))
        w(f"### By {field}")
        w("")
        w(table([field, "museums", "sites"], [[v, c[(v, "museum")], c[(v, "site")]] for v in vals]))
        w("")

    # ---- method ---------------------------------------------------------
    w("## 2. Method")
    w("")
    w("Pipeline (all scripts in `tools/seed/`, Python 3 stdlib only; run in this order):")
    w("")
    w("1. `fetch_egymonuments.py`: egymonuments.gov.eg EN/AR sitemaps plus the portal's own map-pin feed "
      "(`/Umbraco/Api/MapsWebAPI/GetAllMapPins`) to enumerate every museum, archaeological-site and monument page "
      f"({sum(1 for x in egym['pins'] if x['section'] == 'museums')} museums, "
      f"{sum(1 for x in egym['pins'] if x['section'] == 'archaeological-sites')} archaeological sites, "
      f"{sum(1 for x in egym['pins'] if x['section'] == 'monuments')} monuments). Only page URLs and titles are kept.")
    w("2. `fetch_mota_tickets.py`: MoTA's official ticket-price list (PDF, last updated 5 Nov 2024, "
      "https://mota.gov.eg/media/5a2ja2iu/ticket-english-5-11-2024-1.pdf), text-extracted to list which sites/museums are ticketed. "
      "It was used only to decide which sites to include and to set the `mota` flags; no prices or hours were copied into the seed. "
      "The egymonuments portal's archaeological-sites section has only 34 entries, so this list was the main source for ticketed sites.")
    w("3. `fetch_wikipedia_lists.py`: AR `قائمة متاحف مصر` and EN `List of museums in Egypt`. Only row names and section headings are kept, resolved to QIDs. These lists were used to cross-check the museum set.")
    w("4. `fetch_wikidata.py`: museum enumeration and details for every museum, curated site and duplicate QID (labels, aliases, P31, P625, P131 chain to governorate, sitelinks, P856, OSM ids P402/P10689/P11693, P576/P3999/P5817).")
    w("5. `fetch_osm_crosscheck.py`: Overpass, **tags only** (no geometry), used to find missed places and to record OSM element ids for items with an explicit `wikidata=*` tag. No OSM coordinates or names go into `places.json`.")
    w("6. `build_places.py`: merges everything with `sites_curated.json` (hand-curated site list with QIDs, tiers, categories and egymonuments page mapping) and `museums_manual.json` (exclusions, duplicate merges, additions, overrides). The output is sorted by governorate id, then `name.en`.")
    w("7. `validate.py`: stdlib JSON-Schema check against `data/schema/place.schema.json`, plus unique `id`/`wikidataId` and the sort order.")
    w("8. `make_report.py`: writes this file.")
    w("")
    w("`wd_search.py` is the helper used while curating QIDs (Wikidata `wbsearchentities` plus a SPARQL describe query).")
    w("")
    w("Data rules: identity, labels and coordinates come only from Wikidata (CC0). When a Wikidata item has no coordinates, `lat`/`lng` are `null`; they are never filled from OSM or from the portal. "
      "Names: the EN/AR Wikidata labels are used unless an override in the curation files gives a clearer visitor-facing name (written by us). "
      "Governorate: the Wikidata `P131*` chain (also via `P276` / `P361`) to one of the 27 governorates; the defunct Helwan and 6th of October governorates map to Cairo and Giza. "
      "When there are several candidates, Luxor and then Cairo win (old Qena and Giza admin links). "
      "Status is `unknown` unless Wikidata or our curation records a closure.")
    w("")
    w("### Exact SPARQL")
    w("")
    w("Museum enumeration (union of the two results; a single `P131+ wd:Q79` path query times out on WDQS):")
    w("")
    w("```sparql\n" + fetch_wikidata.MUSEUMS_P17.strip() + "\n```")
    w("")
    w("```sparql\n" + fetch_wikidata.MUSEUMS_P131.strip() + "\n```")
    w("")
    w(f"Result: {len(wd['museumQids'])} museum items "
      f"({len(man['exclude'])} excluded, {len(man['merge'])} merged as duplicates, "
      f"{len(man['add'])} added from other sources).")
    w("")
    w("Governorate list (used to build the governorate enum mapping):")
    w("")
    w('```sparql\nSELECT ?g ?gLabel ?ar WHERE { ?g wdt:P31 wd:Q204910 . OPTIONAL{?g rdfs:label ?ar FILTER(lang(?ar)="ar")} SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } }\n```')
    w("")
    w("Bounding-box sanity check for museums lacking `P17=Egypt` (all 49 hits were in Israel, Palestine, Jordan or Saudi Arabia, so none were added):")
    w("")
    w('```sparql\nSELECT DISTINCT ?item ?itemLabel ?coord WHERE {\n  SERVICE wikibase:box {\n    ?item wdt:P625 ?coord .\n    bd:serviceParam wikibase:cornerSouthWest "Point(24.7 22.0)"^^geo:wktLiteral .\n    bd:serviceParam wikibase:cornerNorthEast "Point(36.9 31.7)"^^geo:wktLiteral .\n  }\n  ?item wdt:P31/wdt:P279* wd:Q33506 .\n  FILTER NOT EXISTS { ?item wdt:P17 wd:Q79 }\n  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,ar,mul". }\n}\n```')
    w("")
    w("Detail queries, run in batches of 80 QIDs (`%s` = `VALUES` list):")
    w("")
    for name in ("DETAILS_BASIC", "DETAILS_ALIASES", "DETAILS_TYPES", "DETAILS_ADMIN", "DETAILS_GOV", "DETAILS_MISC"):
        w(f"<details><summary>{name}</summary>\n\n```sparql\n{getattr(fetch_wikidata, name).strip()}\n```\n</details>\n")
    w("Overpass cross-check (tags only):")
    w("")
    w("```\n" + fetch_osm_crosscheck.QUERY.strip() + "\n```")
    w("")

    # ---- decisions ------------------------------------------------------
    w("## 3. Notable decisions")
    w("")
    w("- **One record per visitable, ticketed unit.** Tombs and pyramids sold as add-on tickets inside a site (Great Pyramid, Tutankhamun's tomb, Nefertari, Serapeum and others) are not separate records. They are listed in the curation file's `parts` and should become `prices.extras` of the parent site.")
    w("- **Museums inside sites are separate records**, for example the Imhotep Museum (Saqqara), Karnak Open-Air Museum, Crocodile Museum (Kom Ombo), Aswan Museum (Elephantine), Tell Basta Museum and San el-Hagar Museum.")
    w("- **Galleries inside a museum are not records.** The Tutankhamun galleries and the Khufu Ships Museum are part of GEM, so three Khufu-ships Wikidata items are excluded. The Children's Museum of the Egyptian Museum is part of `egyptian-museum`. The sub-museums of the Agricultural Museum complex in Dokki (Cotton, Plant Resources, Syrian Hall and others) are merged into `agricultural-museum` as aliases.")
    w("- **Moved or closed collections:** the Egyptian Museum (Tahrir) stays `unknown`/open, with a note that the Tutankhamun collection moved to GEM. The old Giza Solar Boat Museum and the Citadel Carriage Museum are `closed`, pointing to GEM and to the Bulaq Royal Carriages Museum. The proposed Alexandria Underwater Museum is `closed` (never built).")
    w("- **Memphis:** the visitable site is the Mit Rahina Open-Air Museum, so it is seeded once as a museum (`mit-rahina-museum`) and not again as a site.")
    w("- **Heritage house-museums** that Wikidata types as museums (Ali Labib House, Beshtak Palace, Gayer-Anderson) are `kind: museum`, even when MoTA sells their tickets on the sites list.")
    w("- **Commercial galleries** typed as museums in Wikidata (Espace Karim Francis, Mashrabia) are kept as `confidence: low` and flagged below.")
    w("- **Sites total ~135, above the ~100 target.** This follows the MoTA ticket list plus the egymonuments archaeological-sites and monuments pages. Most of the extra are `minor` ticketed Delta, Middle Egypt and Western Desert sites, which an app user may still need. To trim, drop non-ticketed `minor` sites (`mota` = false in `sites_curated.json`).")
    w("")
    w("### Wikidata duplicates merged (duplicate -> kept)")
    w("")
    rows = []
    for d, pq in sorted(man["merge"].items(), key=lambda x: x[1]):
        rec = next((p for p in P if p["wikidataId"] == pq), None)
        rows.append([link_q(d), link_q(pq), rec["id"] if rec else "?"])
    for s in sites:
        for d in s.get("dups", []):
            rows.append([link_q(d), link_q(s["qid"]), s["id"]])
    w(table(["duplicate / part item", "kept item", "record"], rows))
    w("")
    w("### Wikidata museum hits excluded")
    w("")
    w(table(["item", "reason"], [[link_q(q), r] for q, r in man["exclude"].items()]))
    w("")

    # ---- human checks ---------------------------------------------------
    w("## 4. Needs human checks")
    w("")
    low = [p for p in P if p["confidence"] == "low"]
    w(f"### Low confidence ({len(low)})")
    w("")
    w(table(["id", "name", "governorate", "why"],
            [[p["id"], p["name"]["en"], p["governorate"],
              "no Wikidata item" if not p["wikidataId"] else (p.get("statusNote") or "curation")] for p in low]))
    w("")
    mc = [by_id[i] for i in notes.get("missingCoords", []) if i in by_id]
    w(f"### Missing coordinates ({len(mc)}): add P625 on Wikidata, then re-run")
    w("")
    w(table(["id", "name", "wikidata"], [[p["id"], p["name"]["en"], link_q(p["wikidataId"])] for p in mc]))
    w("")
    mul = notes.get("multipleCoords", [])
    if mul:
        w(f"### Several Wikidata coordinates ({len(mul)}); the first was used")
        w("")
        w(table(["id", "coordinates"], [[m["id"], "; ".join(f"{a},{b}" for a, b in m["coords"])] for m in mul]))
        w("")
    st = [p for p in P if p["status"] == "closed" or p.get("statusNote")]
    w(f"### Closed / possibly closed / status notes ({len(st)})")
    w("")
    w(table(["id", "status", "note"], [[p["id"], p["status"], p.get("statusNote", "")] for p in st]))
    w("")
    w("### Ambiguous duplicates and overlaps to confirm")
    w("")
    amb = [
        ("heliopolis-open-air-museum vs obelisk-of-senusret-i", "Matariya open-air museum around the obelisk; possibly the same ticketed place."),
        ("minya-museum vs aten-museum", "Both in Minya city; Wikidata may hold two items for the same unopened museum."),
        ("aswan-excavations-museum vs aswan-museum", "Possibly the excavation annex of the Aswan (Elephantine) Museum."),
        ("alexandria-hydrobiological-museum", "Three Wikidata items (aquarium / marine museum / taxidermy museum) at the same point were merged."),
        ("cairo-airport-museum-terminal-2 / -terminal-3", "Two separate MoTA museums; the Wikidata AR label of the T2 item says T3 (fixed by override)."),
        ("hunting-museum-manial vs manial-palace-museum", "A hall inside Manial Palace; could be folded into the palace record."),
        ("citadel-prison-museum vs cairo-citadel", "Inside the Citadel; kept as a museum record because AR Wikipedia lists it as one."),
        ("sultan-hassan-mosque + al-rifai-mosque", "Separate buildings, one shared ticket."),
        ("tombs-of-the-nobles-luxor / el-assasif-tombs / el-khokha-tombs / qurnet-murai", "Kept as 4 records because MoTA sells separate ticket groups; could be merged into one 'Tombs of the Nobles' record."),
        ("rosetta-historic-houses vs rashid-national-museum / alwan-house", "The site record uses the city QID (Q243699)."),
        ("bahariya-oasis-antiquities", "Uses the oasis QID; the ticket covers several Bawiti monuments."),
        ("sadat-museum", "Wikidata places it in Alexandria, but AR Wikipedia lists the Sadat museum at Mit Abu al-Kum (Monufia) and links the same item."),
        ("bibliotheca-alexandrina-* (antiquities, manuscripts, history of science)", "Kept as three museums; the BA library item and the umbrella item are excluded."),
    ]
    w(table(["records", "issue"], amb))
    w("")

    # cross-check leftovers
    used = set()
    for p in P:
        for s in p["sources"]:
            used.add(s["url"])
    unmapped = [x for x in egym["pins"] if x["url_en"] not in used]
    w(f"### egymonuments.gov.eg pages not attached to any record ({len(unmapped)})")
    w("")
    w("Mostly single monuments inside a seeded site, or area overview pages. Attach them or add records if wanted.")
    w("")
    w(table(["section", "page", "title"], [[x["section"], x["url_en"].split("/en/")[1], x.get("title_en", "")] for x in unmapped]))
    w("")
    w("The sunken-monuments (8) and world-heritage (6) sections are thematic pages and are not seeded.")
    w("")
    ours = {p["wikidataId"] for p in P}
    handled = ours | set(man["exclude"]) | set(man["merge"]) | {d for s in sites for d in s.get("dups", [])}
    for lang in ("ar", "en"):
        rows = [r for r in wl.get(lang, {}).get("rows", []) if not (r.get("qid") in handled)]
        res = man.get("listRowResolution", {})
        nq = [r for r in wl.get(lang, {}).get("rows", []) if not r.get("qid")]
        w(f"### {lang.upper()} Wikipedia museum list: rows whose linked QID is not a seeded record ({len(rows)})")
        w("")
        w(f"{len(nq)} further rows have no linked article/QID; they were matched by hand to existing records or added with `wikidataId: null`.")
        w("")
        w(table(["section", "row", "linked article", "QID", "resolution"],
                [[r.get("section") or "", r["label"], r.get("title") or "", r.get("qid") or "",
                  res.get(r.get("qid"), "**unresolved - check**")] for r in rows]))
        w("")
    osm_m = [o for o in osm if o["tourism"] == "museum"]
    osm_wd_missing = [o for o in osm_m if o["wikidata"] and o["wikidata"] not in handled]
    osm_no_wd = [o for o in osm_m if not o["wikidata"]]
    w(f"### OSM cross-check (tags only): {len(osm_m)} `tourism=museum` elements; "
      f"{len(osm_m) - len(osm_no_wd)} carry a wikidata tag, and {len(osm_wd_missing)} of those point outside our set")
    w("")
    w(f"{len(osm_no_wd)} OSM museums have no wikidata tag. Most are the same museums as our records under other names, or sub-exhibits (for example the St Catherine protectorate exhibits and the Pharaonic Village halls). "
      "Ones that looked new were checked and added (Adam Henein Museum, Bayt al-Sinnari). Worth a manual pass:")
    w("")
    w(", ".join(f"`{o['osm']}` {o['name'] or o['nameAr'] or '?'}" for o in osm_no_wd))
    w("")
    w("### MoTA ticket-list rows folded into other records (not separate places)")
    w("")
    w(table(["ticket row(s)", "handled as"], TICKET_ROWS_FOLDED))
    w("")

    # ---- enrichment order -------------------------------------------------
    w("## 5. First 30 places to enrich")
    w("")
    w("All are `tier: major`, ordered hub by hub (Cairo/Giza, Alexandria, Luxor, Aswan, then the rest):")
    w("")
    rows = []
    for i, rid in enumerate(ENRICH_ORDER, 1):
        p = by_id[rid]
        rows.append([i, f"`{rid}`", p["name"]["en"], p["kind"], p["governorate"],
                     "yes" if p["links"].get("egymonuments") else "no"])
    w(table(["#", "id", "name", "kind", "governorate", "egymonuments page"], rows))
    missing_major = [p["id"] for p in P if p["tier"] == "major" and p["id"] not in ENRICH_ORDER]
    if missing_major:
        w("")
        w("Other major records: " + ", ".join(missing_major))
    w("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {OUT}")
    assert len(ENRICH_ORDER) == 30 and all(by_id[r]["tier"] == "major" for r in ENRICH_ORDER)


if __name__ == "__main__":
    main()
